name: Deploy

on:
  workflow_dispatch:
    inputs:
      deploy_message:
        description: 'Alterações realizadas'
        required: true
        default: 'Desc'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install sshpass
        run: sudo apt-get install sshpass

      - name: Deploy to server
        env:
          SERVER_HOST: ${{ secrets.SERVER_HOST }}
          ENVIRONMENT: ${{ secrets.ENVIRONMENT }}
        run: |
          echo "Starting deployment..."
          sshpass -p "$SERVER_PASSWORD" ssh -o StrictHostKeyChecking=no -vvv ${{ secrets.SERVER_USERNAME }}@${{ secrets.SERVER_HOST }} '
          # Debugging: List files and check for permissions
          echo "Checking server environment..."
          ls -la /home/clinipet/backend || exit 1
          which git || exit 1
          which npm || exit 1
          
          # Encerrar o processo atual
          if pgrep -f "node.*start" > /dev/null; then
          pkill -f "node.*start"
          echo "Processo do backend encerrado."
          else
          echo "Nenhum processo do backend encontrado."
          fi
          
          # Fazer o deploy
          cd /home/clinipet/backend &&
          git pull &&
          echo "Código atualizado."
          
          # Instalar dependências e iniciar o serviço
          npm install &&
          echo "$ENVIRONMENT" > .env &&
          nohup npm run start > app.log 2>&1 &
          echo "Backend reiniciado."
          '