name: Deploy

on:
  workflow_dispatch:
    inputs:
      deploy_message:
        description: 'Alterações realizadas'
        required: true
        default: 'Desc'

jobs:
name: Deploy

on:
  workflow_dispatch:
    inputs:
      deploy_message:
        description: 'Alterações realizadas'
        required: true
        default: 'Desc'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install sshpass
        run: sudo apt-get install sshpass

      - name: Deploy to server
        env:
          SERVER_PASSWORD: ${{ secrets.SERVER_PASSWORD }}
          SERVER_USERNAME: ${{ secrets.SERVER_USERNAME }}
          SERVER_HOST: ${{ secrets.SERVER_HOST }}
          ENVIRONMENT: ${{ secrets.ENVIRONMENT }}
        run: |
          # Encerrar o processo atual
          sshpass -p "$SERVER_PASSWORD" ssh -o StrictHostKeyChecking=no $SERVER_USERNAME@$SERVER_HOST '
            if pgrep -f "node.*start" > /dev/null; then
              pkill -f "node.*start"
              echo "Processo do backend encerrado."
            else
              echo "Nenhum processo do backend encontrado."
            fi
          '

          # Fazer o deploy
          sshpass -p "$SERVER_PASSWORD" ssh -o StrictHostKeyChecking=no $SERVER_USERNAME@$SERVER_HOST '
            cd /home/clinipet/backend &&
            git pull &&
            echo "Código atualizado."

          # Instalar dependências e iniciar o serviço
          sshpass -p "$SERVER_PASSWORD" ssh -o StrictHostKeyChecking=no $SERVER_USERNAME@$SERVER_HOST '
            npm install &&
            echo "$ENVIRONMENT" > .env &&
            nohup npm run start > app.log 2>&1 &
            echo "Backend reiniciado."
          '